# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!
target 'NBCHackathon' do
  pod 'ESTabBarController'
  pod 'EZSwiftExtensions'
  pod 'MGSwipeTableCell'

  pod 'Alamofire', '~> 3.0'
end

target 'NBCHackathonTests' do

end

target 'NBCHackathonUITests' do

end

